version: '3'

services:      
  db:
    container_name: postgres_server_references_service
    image: postgres:latest
    ports:
      - "5434:5432"
    env_file:
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: references_service:0.1    
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/references_service    

volumes:
  postgres_data:
