apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-references-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-references-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: references_db
          volumeMounts:
            - name: postgres-references-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-references-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-references-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
