apiVersion: v1
kind: Secret
metadata:
  name: postgres-references-secrets
type: Opaque
data:
  POSTGRES_USER: ZGJfdXNlcg==
  POSTGRES_PASSWORD: dGVzdA==
  POSTGRES_HOST: cG9zdGdyZXNfc2VydmVyX3JlZmVyZW5jZXNfc2VydmljZQ==
  POSTGRES_DB: ZGJfcmVmZXJlbmNlX3NlcnZpY2U=
